### ISSUE TITLE
build fails apparently because repository is missing _funcs.asm

### ISSUE THREAD

**Issue by artkiver** [nop00/shipping-is-a-feature#1]
% git clone https://github.com/nop00/shipping-is-a-feature/i
% cd shipping-is-a-feature
% pceas demo.asm
PC Engine Assembler 3.22, Dec  7 2016)

pass 1
#[1]   demo.asm
   78  :O000                  .include "../_funcs.asm"
       Can not open file!
# 1 error(s)
% p ../meet-the-supergrafx/_funcs.asm .
% ls -alFh
total 3240
drwxr-xr-x  51 grey  staff   1.7K Dec  7 09:01 ./
drwxr-xr-x   6 grey  staff   204B Dec  7 09:05 ../
drwxr-xr-x  13 grey  staff   442B Dec  7 08:56 .git/
-rw-r--r--   1 grey  staff   6.6K Dec  7 08:56 README.md
-rw-r--r--   1 grey  staff    34K Dec  7 08:56 _font.asm
-rw-r--r--   1 grey  staff    69B Dec  7 09:03 _funcs.asm
-rw-r--r--   1 grey  staff   6.8K Dec  7 08:56 _macros.asm
-rw-r--r--   1 grey  staff   2.0K Dec  7 08:56 _macrosbase.asm
-rw-r--r--   1 grey  staff   1.5K Dec  7 08:56 _sound.asm
-rw-r--r--   1 grey  staff   485B Dec  7 08:56 _transition.asm
drwxr-xr-x  10 grey  staff   340B Dec  7 08:56 azasel/
-rw-r--r--   1 grey  staff    27K Dec  7 08:56 buenzli_bg.asm
-rw-r--r--   1 grey  staff    68K Dec  7 08:56 buenzli_bg_data.asm
-rw-r--r--   1 grey  staff   170K Dec  7 08:56 buenzli_bg_data2.asm
-rw-r--r--   1 grey  staff   4.2K Dec  7 08:56 common.asm
-rw-r--r--   1 grey  staff    11K Dec  7 08:56 credits.asm
-rw-r--r--   1 grey  staff    54K Dec  7 08:56 credits_data1.asm
-rw-r--r--   1 grey  staff    55K Dec  7 08:56 credits_data2.asm
-rw-r--r--   1 grey  staff    71K Dec  7 08:56 credits_data3.asm
-rw-r--r--   1 grey  staff    27K Dec  7 08:56 credits_data4.asm
-rw-r--r--   1 grey  staff   7.3K Dec  7 08:56 credits_data5.asm
-rw-r--r--   1 grey  staff   8.4K Dec  7 08:56 demo.asm
-rw-r--r--   1 grey  staff   4.7K Dec  7 08:56 demo_logo.asm
-rw-r--r--   1 grey  staff    84K Dec  7 08:56 demo_logo_data.asm
-rw-r--r--   1 grey  staff    53K Dec  7 08:56 demo_logo_data2.asm
-rw-r--r--   1 grey  staff    21K Dec  7 08:56 demo_logo_data3.asm
-rw-r--r--   1 grey  staff   341B Dec  7 08:56 fadetowhite.asm
-rw-r--r--   1 grey  staff    23K Dec  7 08:56 font01.asm
-rw-r--r--   1 grey  staff    21K Dec  7 08:56 font02.asm
-rw-r--r--   1 grey  staff    19K Dec  7 08:56 fontasteroids.asm
-rw-r--r--   1 grey  staff   2.4K Dec  7 08:56 goodbye.asm
-rw-r--r--   1 grey  staff    77K Dec  7 08:56 goodbye_data.asm
-rw-r--r--   1 grey  staff    10K Dec  7 08:56 greets.asm
-rw-r--r--   1 grey  staff    50K Dec  7 08:56 greets_data.asm
-rw-r--r--   1 grey  staff    94K Dec  7 08:56 greets_data2.asm
-rw-r--r--   1 grey  staff   9.6K Dec  7 08:56 greets_data3.asm
drwxr-xr-x  13 grey  staff   442B Dec  7 08:56 music/
-rw-r--r--   1 grey  staff   4.1K Dec  7 08:56 punkfloyd_logo.asm
-rw-r--r--   1 grey  staff    75K Dec  7 08:56 punkfloyd_logo_data.asm
-rw-r--r--   1 grey  staff   6.1K Dec  7 08:56 rasters.asm
-rw-r--r--   1 grey  staff    59K Dec  7 08:56 rasters_data.asm
-rw-r--r--   1 grey  staff    55K Dec  7 08:56 transitions.asm
-rw-r--r--   1 grey  staff   2.7K Dec  7 08:56 warning.asm
-rw-r--r--   1 grey  staff    45K Dec  7 08:56 warning_data.asm
-rw-r--r--   1 grey  staff    54K Dec  7 08:56 warning_data2.asm
-rw-r--r--   1 grey  staff    47K Dec  7 08:56 warning_data3.asm
-rw-r--r--   1 grey  staff    31K Dec  7 08:56 wazza_data1.asm
-rw-r--r--   1 grey  staff    29K Dec  7 08:56 wazza_data2.asm
-rw-r--r--   1 grey  staff    31K Dec  7 08:56 wazza_data3.asm
-rw-r--r--   1 grey  staff    30K Dec  7 08:56 wazza_data4.asm
-rw-r--r--   1 grey  staff    31K Dec  7 08:56 wazza_data5.asm

% pceas demo.asm
PC Engine Assembler 3.22, Dec  7 2016)

pass 1
#[1]   demo.asm
   78  :O000                  .include "../_funcs.asm"
       Can not open file!
# 1 error(s)

So, it appears as though the _funcs.asm file expected by the demo.asm build is not present in this repository. However, even when copying that _funcs.asm file from another repository also by nop00 that is insufficient. Both meet-the-supergrafx and le-petit-chat-n-est-pas-mort produce demo.pce when pceas demo.asm is run (though I have not yet tested them in mednafen nor hardware yet presumably they will run correctly?) However, this repository seems to have issues and even presuming perhaps you shared a funcs.asm call between projects was perhaps naive, so at the moment I can't currently reproduce this build to test. :)

**Comment by nop00** [comment]
Fixed, thanks for the report!
You were right to import the file from another project (it didn't really change over the years), what you were missing was the correct inclusion path in demo.asm.
Anyway, it's all good now, building and running fine, thanks again!
